#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generates deploy/k8s/*.yaml so every service gets identical, hardened settings.

    python deploy/k8s/generate.py && kubectl apply -k deploy/k8s
"""
import json
from pathlib import Path

OUT = Path(__file__).parent
NS = "bookmind"
IMAGE = "ghcr.io/OWNER/bookmind:2.0.0"  # set by CI (kustomize edit set image) — see .github/workflows

SERVICES = {
    #          replicas, min/max HPA,  cpu req, mem limit, extra env
    "gateway":  dict(replicas=2, hpa=(2, 10), cpu="100m", mem="256Mi", env={"BOOKMIND_TRUST_PROXY": "true"}),
    "catalog":  dict(replicas=2, hpa=None, cpu="50m", mem="256Mi", env={}),
    "search":   dict(replicas=2, hpa=(2, 8), cpu="100m", mem="384Mi", env={}),
    "research": dict(replicas=2, hpa=(2, 6), cpu="100m", mem="256Mi", env={
        "BOOKMIND_OLLAMA_URL": "http://ollama:11434/api/chat",
        "BOOKMIND_OLLAMA_MODEL": "llama3.2",
        "BOOKMIND_OLLAMA_TIMEOUT_S": "120",
        "BOOKMIND_MAX_CONCURRENT_GENERATIONS": "2"}),
}


def dump(name, docs):
    text = "\n---\n".join(json.dumps(d, indent=2) for d in docs)  # JSON is valid YAML
    (OUT / f"{name}.yaml").write_text(f"# Generated by generate.py — edit that, not this.\n{text}\n")


def labels(name):
    return {"app.kubernetes.io/name": name, "app.kubernetes.io/part-of": "bookmind"}


def container(name, extra_env, cpu, mem, volume_mounts=()):
    env = [{"name": "SERVICE", "value": name}]
    env += [{"name": k, "value": v} for k, v in extra_env.items()]
    env += [
        {"name": "BOOKMIND_INTERNAL_TOKEN_FILE", "value": "/run/secrets/bookmind/internal_token"},
        {"name": "BOOKMIND_REDIS_PASSWORD_FILE", "value": "/run/secrets/bookmind/redis_password"},
    ]
    if name == "gateway":
        env.append({"name": "BOOKMIND_AUTH_PASSWORD_FILE", "value": "/run/secrets/bookmind/auth_password"})
    return {
        "name": name,
        "image": IMAGE,
        "imagePullPolicy": "IfNotPresent",
        "ports": [{"name": "http", "containerPort": 8000}],
        "envFrom": [{"configMapRef": {"name": "bookmind-config"}}],
        "env": env,
        "resources": {"requests": {"cpu": cpu, "memory": "96Mi"}, "limits": {"memory": mem}},
        "startupProbe": {"httpGet": {"path": "/healthz", "port": "http"}, "periodSeconds": 2, "failureThreshold": 30},
        "livenessProbe": {"httpGet": {"path": "/healthz", "port": "http"}, "periodSeconds": 10, "failureThreshold": 3},
        "readinessProbe": {"httpGet": {"path": "/readyz", "port": "http"}, "periodSeconds": 5, "failureThreshold": 2},
        # Let the load balancer stop sending traffic before the process starts draining.
        "lifecycle": {"preStop": {"exec": {"command": ["python", "-c", "import time; time.sleep(5)"]}}},
        "securityContext": {
            "runAsNonRoot": True, "runAsUser": 10001, "runAsGroup": 10001,
            "readOnlyRootFilesystem": True, "allowPrivilegeEscalation": False,
            "capabilities": {"drop": ["ALL"]}, "seccompProfile": {"type": "RuntimeDefault"},
        },
        "volumeMounts": [
            {"name": "tmp", "mountPath": "/tmp"},
            {"name": "secrets", "mountPath": "/run/secrets/bookmind", "readOnly": True},
            {"name": "flags", "mountPath": "/app/deploy/config", "readOnly": True},
            *volume_mounts,
        ],
    }


def pod_spec(c, extra_volumes=()):
    return {
        "automountServiceAccountToken": False,
        "terminationGracePeriodSeconds": 30,
        "securityContext": {"fsGroup": 10001},
        "topologySpreadConstraints": [{
            "maxSkew": 1, "topologyKey": "kubernetes.io/hostname", "whenUnsatisfiable": "ScheduleAnyway",
            "labelSelector": {"matchLabels": {"app.kubernetes.io/name": c["name"]}}}],
        "containers": [c],
        "volumes": [
            {"name": "tmp", "emptyDir": {"sizeLimit": "64Mi"}},
            {"name": "secrets", "secret": {"secretName": "bookmind-secrets"}},
            {"name": "flags", "configMap": {"name": "bookmind-flags"}},
            *extra_volumes,
        ],
    }


def service(name, port=8000):
    return {"apiVersion": "v1", "kind": "Service", "metadata": {"name": name, "namespace": NS, "labels": labels(name)},
            "spec": {"selector": {"app.kubernetes.io/name": name}, "ports": [{"name": "http", "port": port, "targetPort": port if name in ("redis", "ollama") else "http"}]}}


def pdb(name):
    return {"apiVersion": "policy/v1", "kind": "PodDisruptionBudget", "metadata": {"name": name, "namespace": NS},
            "spec": {"minAvailable": 1, "selector": {"matchLabels": {"app.kubernetes.io/name": name}}}}


docs = []
for name, cfg in SERVICES.items():
    meta = {"name": name, "namespace": NS, "labels": labels(name)}
    docs.append({
        "apiVersion": "apps/v1", "kind": "Deployment", "metadata": meta,
        "spec": {
            "replicas": cfg["replicas"],
            "revisionHistoryLimit": 5,
            "selector": {"matchLabels": {"app.kubernetes.io/name": name}},
            # Zero-downtime rolling update: never drop below desired capacity.
            "strategy": {"type": "RollingUpdate", "rollingUpdate": {"maxUnavailable": 0, "maxSurge": 1}},
            "template": {
                "metadata": {"labels": labels(name), "annotations": {"prometheus.io/scrape": "true", "prometheus.io/port": "8000"}},
                "spec": pod_spec(container(name, cfg["env"], cfg["cpu"], cfg["mem"])),
            },
        },
    })
    docs.append(service(name))
    docs.append(pdb(name))
    if cfg["hpa"]:
        lo, hi = cfg["hpa"]
        docs.append({
            "apiVersion": "autoscaling/v2", "kind": "HorizontalPodAutoscaler", "metadata": {"name": name, "namespace": NS},
            "spec": {"scaleTargetRef": {"apiVersion": "apps/v1", "kind": "Deployment", "name": name},
                     "minReplicas": lo, "maxReplicas": hi,
                     "metrics": [{"type": "Resource", "resource": {"name": "cpu", "target": {"type": "Utilization", "averageUtilization": 70}}}],
                     "behavior": {"scaleDown": {"stabilizationWindowSeconds": 300}}},
        })

# notebook: SQLite has exactly one writer -> a single-replica StatefulSet with its own volume.
nb = container("notebook", {}, "50m", "256Mi", [{"name": "data", "mountPath": "/app/var"}])
docs.append({
    "apiVersion": "apps/v1", "kind": "StatefulSet", "metadata": {"name": "notebook", "namespace": NS, "labels": labels("notebook")},
    "spec": {
        "serviceName": "notebook", "replicas": 1,
        "selector": {"matchLabels": {"app.kubernetes.io/name": "notebook"}},
        "template": {"metadata": {"labels": labels("notebook"), "annotations": {"prometheus.io/scrape": "true", "prometheus.io/port": "8000"}},
                     "spec": pod_spec(nb)},
        "volumeClaimTemplates": [{"metadata": {"name": "data"},
                                  "spec": {"accessModes": ["ReadWriteOnce"], "resources": {"requests": {"storage": "1Gi"}}}}],
    },
})
docs.append(service("notebook"))
dump("services", docs)

# ------------------------------------------------------------------ stateful infrastructure
redis = {
    "apiVersion": "apps/v1", "kind": "StatefulSet", "metadata": {"name": "redis", "namespace": NS, "labels": labels("redis")},
    "spec": {
        "serviceName": "redis", "replicas": 1,
        "selector": {"matchLabels": {"app.kubernetes.io/name": "redis"}},
        "template": {"metadata": {"labels": labels("redis")}, "spec": {
            "automountServiceAccountToken": False,
            "securityContext": {"runAsNonRoot": True, "runAsUser": 999, "fsGroup": 999, "seccompProfile": {"type": "RuntimeDefault"}},
            "containers": [{
                "name": "redis", "image": "redis:7.4-alpine",
                "command": ["sh", "-c", 'exec redis-server --requirepass "$(cat /run/secrets/bookmind/redis_password)" --appendonly yes --maxmemory 256mb --maxmemory-policy noeviction'],
                "ports": [{"containerPort": 6379, "name": "redis"}],
                "resources": {"requests": {"cpu": "50m", "memory": "64Mi"}, "limits": {"memory": "320Mi"}},
                "readinessProbe": {"exec": {"command": ["sh", "-c", 'redis-cli -a "$(cat /run/secrets/bookmind/redis_password)" --no-auth-warning ping | grep PONG']}, "periodSeconds": 5},
                "securityContext": {"allowPrivilegeEscalation": False, "readOnlyRootFilesystem": True, "capabilities": {"drop": ["ALL"]}},
                "volumeMounts": [{"name": "data", "mountPath": "/data"}, {"name": "secrets", "mountPath": "/run/secrets/bookmind", "readOnly": True}],
            }],
            "volumes": [{"name": "secrets", "secret": {"secretName": "bookmind-secrets"}}],
        }},
        "volumeClaimTemplates": [{"metadata": {"name": "data"}, "spec": {"accessModes": ["ReadWriteOnce"], "resources": {"requests": {"storage": "1Gi"}}}}],
    },
}
redis_svc = service("redis", 6379)
redis_svc["spec"]["ports"] = [{"name": "redis", "port": 6379, "targetPort": 6379}]
ollama = {
    "apiVersion": "apps/v1", "kind": "StatefulSet", "metadata": {"name": "ollama", "namespace": NS, "labels": labels("ollama")},
    "spec": {
        "serviceName": "ollama", "replicas": 1,
        "selector": {"matchLabels": {"app.kubernetes.io/name": "ollama"}},
        "template": {"metadata": {"labels": labels("ollama")}, "spec": {
            "automountServiceAccountToken": False,
            "containers": [{
                "name": "ollama", "image": "ollama/ollama:latest",
                "ports": [{"containerPort": 11434, "name": "http"}],
                "resources": {"requests": {"cpu": "1", "memory": "4Gi"}, "limits": {"memory": "8Gi"}},
                # GPU nodes: add  limits: {nvidia.com/gpu: 1}
                "readinessProbe": {"httpGet": {"path": "/api/tags", "port": 11434}, "periodSeconds": 10},
                "volumeMounts": [{"name": "models", "mountPath": "/root/.ollama"}],
            }],
        }},
        "volumeClaimTemplates": [{"metadata": {"name": "models"}, "spec": {"accessModes": ["ReadWriteOnce"], "resources": {"requests": {"storage": "20Gi"}}}}],
    },
}
ollama_svc = service("ollama", 11434)
ollama_svc["spec"]["ports"] = [{"name": "http", "port": 11434, "targetPort": 11434}]
dump("infrastructure", [redis, redis_svc, ollama, ollama_svc])

# ------------------------------------------------------------------ zero-trust networking
def policy(name, pod, ingress_from=None, egress_to=None):
    spec = {"podSelector": {"matchLabels": {"app.kubernetes.io/name": pod}} if pod else {}, "policyTypes": []}
    if ingress_from is not None:
        spec["policyTypes"].append("Ingress")
        spec["ingress"] = ingress_from
    if egress_to is not None:
        spec["policyTypes"].append("Egress")
        spec["egress"] = egress_to
    return {"apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy", "metadata": {"name": name, "namespace": NS}, "spec": spec}


def from_pods(*names, port=8000):
    return {"from": [{"podSelector": {"matchLabels": {"app.kubernetes.io/name": n}}} for n in names], "ports": [{"port": port}]}


def to_pods(*names, port=8000):
    return {"to": [{"podSelector": {"matchLabels": {"app.kubernetes.io/name": n}}} for n in names], "ports": [{"port": port}]}


dns = {"to": [{"namespaceSelector": {}, "podSelector": {"matchLabels": {"k8s-app": "kube-dns"}}}], "ports": [{"port": 53, "protocol": "UDP"}, {"port": 53, "protocol": "TCP"}]}
scrape = {"from": [{"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "monitoring"}}}], "ports": [{"port": 8000}]}
ingress_ctrl = {"from": [{"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "ingress-nginx"}}}], "ports": [{"port": 8000}]}
otlp = {"to": [{"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "monitoring"}}}], "ports": [{"port": 4318}]}

dump("networkpolicies", [
    policy("default-deny", None, ingress_from=[], egress_to=[]),
    policy("gateway", "gateway", [ingress_ctrl, scrape], [dns, otlp, to_pods("catalog", "search", "research", "notebook"), to_pods("redis", port=6379)]),
    policy("catalog", "catalog", [from_pods("gateway", "search", "research"), scrape], [dns, otlp]),
    policy("search", "search", [from_pods("gateway", "research"), scrape], [dns, otlp, to_pods("catalog", "notebook"), to_pods("redis", port=6379)]),
    policy("research", "research", [from_pods("gateway"), scrape], [dns, otlp, to_pods("search", "catalog"), to_pods("redis", port=6379), to_pods("ollama", port=11434)]),
    policy("notebook", "notebook", [from_pods("gateway", "search"), scrape], [dns, otlp, to_pods("redis", port=6379)]),
    policy("redis", "redis", [from_pods("gateway", "search", "research", "notebook", port=6379)], []),
    # Ollama may reach the internet (to pull weights) but only research may reach Ollama.
    policy("ollama", "ollama", [from_pods("research", port=11434)], [dns, {"ports": [{"port": 443}]}]),
])
print("generated services.yaml, infrastructure.yaml, networkpolicies.yaml")
